name: Frontend CI

on:
  push:
    branches:
      - frontend_cicd_dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set working directory
        run: cd speed-frontend

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: cd speed-frontend && npm install

      # - name: Run Tests
      #   run: npm test

      - name: Build
        run: cd speed-frontend && npm run build

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: dist/
