name: Frontend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set working directory
        run: cd speed-frontend

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: cd speed-frontend && npm install

      - name: Run Tests
        run: cd speed-frontend && npm run test:ci

      - name: Build
        run: cd speed-frontend && npm run build
